[build]
  publish = "build/web"
  command = "./build.sh"

[build.environment]
  # Use Ubuntu 20.04 which has better compatibility
  NODE_VERSION = "18"
  # Add any additional environment variables here
  # SUPABASE_URL and SUPABASE_ANON_KEY should be set in Netlify dashboard

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
