name: memtechnology_shop_v2
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.0
  uuid: ^4.5.0
  intl: ^0.18.0
  image_picker: ^1.0.0
  pdf: ^3.10.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true